// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLl874gG5hYXxKrvGfwjwbSeSCkeoFS0',
    appId: '1:881938428215:android:8a2572943107aa20ae2ab2',
    messagingSenderId: '881938428215',
    projectId: 'nilu-e70c4',
    storageBucket: 'nilu-e70c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVmYDIg40w3c3vIwOfVDKd15l0452l9fg',
    appId: '1:881938428215:ios:74b28e6686421b0eae2ab2',
    messagingSenderId: '881938428215',
    projectId: 'nilu-e70c4',
    storageBucket: 'nilu-e70c4.appspot.com',
    androidClientId: '881938428215-k57tdhemqi3lt3quur7o98v1n3kog1lb.apps.googleusercontent.com',
    iosClientId: '881938428215-4422s4v4vllq49qmjnbkbmkessp87ic2.apps.googleusercontent.com',
    iosBundleId: 'com.shokhrukhbek.nilu',
  );
}
