import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // ! generic
          'ok': 'Ok',
          'cancel': 'Cancel',
          'yes': 'Yes',
          'no': 'No',
          'back': 'Back',
          'next': 'Next',
          'done': 'Done',
          'retry': 'Retry',
          'close': 'Close',
          'delete': 'Delete',
          'edit': 'Edit',
          'save': 'Save',
          'send': 'Send',
          'search': 'Search',
          'clear': 'Clear',
          'total': 'Total',
          'reset': 'Reset',
          'apply': 'Apply',
          'not_found': 'Not found',
          'confirm': 'Confirm',
          'change': 'Change',
          'currency': 'Currency',
          'continue': 'Continue',
          'name': 'Name',
          'business_name': 'Business name',
          'phone': 'Phone',
          'main_currency': 'Main currency',
          'secondary_currency': 'Secondary currency',
          'unnamed_client': 'Unnamed client',
          'date': 'Date',
          'debt': 'Debt',
          'success': 'Success',
          'error': 'Error',
          'filter': 'Filter',
          'sort': 'Sort',
          'something_went_wrong': 'Something went wrong',
          'select_image_source': 'Select image source',
          'gallery': 'Gallery',
          'camera': 'Camera',
          'english': 'English',
          'russian': 'Russian',
          'uzbek': 'Uzbek',
          'spanish': 'Spanish',
          'payment': 'Payment',
          'all': 'All',
          // ! login
          'login': 'Login',
          'restore_account': 'Restore account',
          'app_description': 'Easily manage your sales, income, and products',
          'not_phone_number': 'Please enter a valid phone number',
          // ! otp
          'verification': 'Verification',
          'otp_description': 'We sent SMS code to number',
          'resend_code': 'Resend code',
          // ! register
          'account_info': 'Account info',
          'save_and_continue': 'Save and continue',
          'fill_required_fields': 'Please fill all required fields',
          // ! home
          'exchange_rate': 'Exchange rate',
          'todays_sales': 'Today\'s sales',
          'all_sales': 'All sales',
          'clients': 'Clients',
          'products': 'Products',
          'new_sale': 'New sale',
          'add_product': 'Add product',
          'statistics': 'Statistics',
          'categories': 'Categories',
          'settings': 'Settings',
          'support': 'Support',
          'no_secondary_currency': 'No secondary currency',
          // ! sales
          'all_clients': 'All clients',
          'client': 'Client',
          'any_date': 'Any date',
          'reciept': 'Reciept',
          'delete_sale': 'Delete sale',
          'delete_sale_confirmation':
              'Are you sure you want to delete this sale?',
          'sale': 'Sale',
          // ! add sale
          'select_items': 'Select items',
          'in_stock': 'In stock',
          'selected': 'selected',
          'select_quantity': 'Select quantity',
          'not_enough': 'Not enough',
          // ! cart
          'add_discount': 'Add discount',
          'add_payment': 'Add payment',
          'discount': 'Discount',
          'add_comment': 'Add comment',
          'add_another': 'Add another',
          'paid': 'Paid',
          'discounted_price': 'Discounted price',
          'remaining': 'Remaining',
          'unpaid_amount': 'Unpaid amount',
          'unpaid_amount_description':
              'How do you want to save the remaining amount?',
          'order_created': 'Order created',
          'overpaid': 'Overpaid',
          'enter_discount': 'Enter discount',
          'comment': 'Comment',
          'enter_comment': 'Enter comment',
          'no_products_in_cart': 'No products in cart',
          // ! edit sale
          'order_updated': 'Order updated',
          // ! statistics
          'today': 'Today',
          'last_week': 'Last week',
          'last_month': 'Last month',
          'last_year': 'Last year',
          'all_time': 'All time',
          'total_sales': 'Total sales',
          'products_sold': 'Products sold',
          'no_products_sold': 'No products sold',
          'sold': 'Sold',
          // ! clients
          'no_phone': 'No phone',
          'no_note': 'No note',
          'no_debt': 'No debt',
          'delete_client': 'Delete client',
          'delete_client_confirmation':
              'Are you sure you want to delete this client?',
          'view_orders': 'View orders',
          // ! add client
          'new_client': 'New client',
          'note': 'Note',
          'client_added': 'Client added',
          // ! edit client
          'edit_client': 'Edit client',
          'client_updated': 'Client updated',
          // ! select client
          'select_client': 'Select client',
          // ! products
          'product_name': 'Product name',
          'category': 'Category',
          'code': 'Code',
          'price': 'Price',
          'stock_in_out': 'Stock in/out',
          'edit_product': 'Edit product',
          'make_sale': 'Make sale',
          'delete_product': 'Delete product',
          'delete_product_confirmation':
              'Are you sure you want to delete this product?',
          'you_applied_filter': 'You applied filter',
          'show_all': 'Show all',
          'deleted': 'deleted',
          'add_new_category': 'Add new category',
          // ! add product
          'new_product': 'New product',
          'no_category': 'No category',
          'total_stock': 'Total stock',
          'product_name_required': 'Product name is required',
          'product_price_required': 'Product price is required',
          'product_quantity_required': 'Product quantity is required',
          'price_negative': 'Price can\'t be negative',
          'quantity_negative': 'Quantity can\'t be negative',
          'product_added': 'Product added',
          // ! edit product
          'product_updated': 'Product updated',
          // ! exchange rate
          'auto_update': 'Auto update',
          'bank_rate': 'Bank rate',
          'new_rate': 'New rate',
          'auto_adjust': 'Auto adjust',
          'adjust_by': 'Adjust by',
          'manual_input': 'Manual input',
          'enter_amount': 'Enter amount',
          'exchange_rate_saved': 'Exchange rate saved',
          // ! categories
          'delete_category': 'Delete category',
          'delete_category_confirmation':
              'Are you sure you want to delete this category?',
          'new_category': 'New category',
          'category_name': 'Category name',
          'category_deleted': 'Category deleted',
          'error_deleting_category': 'Error deleting category',
          'edit_category': 'Edit category',
          'category_updated': 'Category updated',
          // ! settings
          'logout': 'Logout',
          'logout_confirmation': 'Are you sure you want to logout?',
          'notifications': 'Notifications',
          'dark_mode': 'Dark mode',
          'language': 'Language',
          'select_language': 'Select language',
          // ! support
          'support_description': 'Need any assistance? Feel free to contact us',
        },
        'es_ES': {
          // ! generic
          'ok': 'Ok',
          'cancel': 'Cancelar',
          'yes': 'Si',
          'no': 'No',
          'back': 'Atrás',
          'next': 'Siguiente',
          'done': 'Hecho',
          'retry': 'Reintentar',
          'close': 'Cerrar',
          'delete': 'Eliminar',
          'edit': 'Editar',
          'save': 'Guardar',
          'send': 'Enviar',
          'search': 'Buscar',
          'clear': 'Limpiar',
          'total': 'Total',
          'reset': 'Reiniciar',
          'apply': 'Aplicar',
          'not_found': 'No encontrado',
          'confirm': 'Confirmar',
          'change': 'Cambiar',
          'currency': 'Moneda',
          'continue': 'Continuar',
          'name': 'Nombre',
          'business_name': 'Nombre de la empresa',
          'phone': 'Teléfono',
          'main_currency': 'Moneda principal',
          'secondary_currency': 'Moneda secundaria',
          'unnamed_client': 'Cliente sin nombre',
          'date': 'Fecha',
          'debt': 'Deuda',
          'success': 'Éxito',
          'error': 'Error',
          'filter': 'Filtrar',
          'sort': 'Ordenar',
          'something_went_wrong': 'Algo salió mal',
          'select_image_source': 'Seleccionar origen de la imagen',
          'gallery': 'Galería',
          'camera': 'Cámara',
          'english': 'Inglés',
          'russian': 'Ruso',
          'uzbek': 'Uzbeco',
          'spanish': 'Español',
          'payment': 'Pago',
          'all': 'Todo',
          // ! login
          'login': 'Iniciar sesión',
          'restore_account': 'Restaurar cuenta',
          'app_description':
              'Gestiona fácilmente tus ventas, ingresos y productos',
          'not_phone_number': 'Please enter a valid phone number',
          // ! otp
          'verification': 'Verificación',
          'otp_description': 'Hemos enviado un código SMS a tu número',
          'resend_code': 'Reenviar código',
          // ! register
          'account_info': 'Información de la cuenta',
          'save_and_continue': 'Guardar y continuar',
          'fill_required_fields':
              'Por favor, rellene todos los campos requeridos',
          // ! home
          'exchange_rate': 'Tipo de cambio',
          'todays_sales': 'Ventas de hoy',
          'all_sales': 'Todas las ventas',
          'clients': 'Clientes',
          'products': 'Productos',
          'new_sale': 'Nueva venta',
          'add_product': 'Agregar producto',
          'statistics': 'Estadísticas',
          'categories': 'Categorías',
          'settings': 'Configuración',
          'support': 'Soporte',
          'no_secondary_currency': 'No hay moneda secundaria',
          // ! sales
          'all_clients': 'Todos los clientes',
          'client': 'Cliente',
          'any_date': 'Cualquier fecha',
          'reciept': 'Recibo',
          'delete_sale': 'Eliminar venta',
          'delete_sale_confirmation':
              '¿Está seguro de que desea eliminar esta venta?',
          'sale': 'Venta',
          // ! add sale
          'select_items': 'Seleccionar articulos',
          'in_stock': 'En surtir',
          'selected': 'Seleccionado',
          'select_quantity': 'Seleccionar cantidad',
          'not_enough': 'No hay suficiente',
          // ! cart
          'add_discount': 'Agregar descuento',
          'add_payment': 'Agregar pago',
          'discount': 'Descuento',
          'add_comment': 'Agregar comentario',
          'add_another': 'Agregar otro',
          'paid': 'Pagado',
          'discounted_price': 'Precio con descuento',
          'remaining': 'Restante',
          'unpaid_amount': 'Cantidad no pagada',
          'unpaid_amount_description':
              '¿Cómo quiere guardar el monto restante?',
          'order_created': 'Orden creada',
          'overpaid': 'Pagado en exceso',
          'enter_discount': 'Ingrese descuento',
          'comment': 'Comentario',
          'enter_comment': 'Ingrese comentario',
          'no_products_in_cart': 'No hay productos en el carrito',
          // ! edit sale
          'order_updated': 'Orden actualizada',
          // ! statistics
          'today': 'Hoy',
          'last_week': 'Última semana',
          'last_month': 'Último mes',
          'last_year': 'Último año',
          'all_time': 'Todo el tiempo',
          'total_sales': 'Ventas totales',
          'products_sold': 'Productos vendidos',
          'no_products_sold': 'No hay productos vendidos',
          'sold': 'Vendido',
          // ! clients
          'no_phone': 'Sin teléfono',
          'no_notes': 'Sin notas',
          'no_debts': 'Sin deudas',
          'delete_client': 'Eliminar cliente',
          'delete_client_confirmation':
              '¿Está seguro de que desea eliminar este cliente?',
          'view_orders': 'Ver ordenes',
          // ! add client
          'new_client': 'Nuevo cliente',
          'note': 'Nota',
          'client_added': 'Cliente agregado',
          // ! edit client
          'edit_client': 'Editar cliente',
          'client_updated': 'Cliente actualizado',
          // ! select client
          'select_client': 'Seleccionar cliente',
          // ! products
          'product_name': 'Nombre del producto',
          'category': 'Categoría',
          'code': 'Código',
          'price': 'Precio',
          'stock_in_out': 'Agregar/eliminar',
          'edit_product': 'Editar producto',
          'make_sale': 'Hacer venta',
          'delete_product': 'Eliminar producto',
          'delete_product_confirmation':
              '¿Está seguro de que desea eliminar este producto?',
          'you_applied_filter': 'Usted aplicó un filtro',
          'show_all': 'Mostrar todo',
          'deleted': 'Eliminado',
          'add_new_category': 'Agregar nueva categoría',
          // ! add product
          'new_product': 'Nuevo producto',
          'no_category': 'No hay categoría',
          'total_stock': 'Existencias totales',
          'product_name_required': 'El nombre del producto es requerido',
          'product_price_required': 'El precio del producto es requerido',
          'product_quantity_required': 'La cantidad del producto es requerida',
          'price_negative': 'El precio no puede ser negativo',
          'quantity_negative': 'La cantidad no puede ser negativa',
          'product_added': 'Producto agregado',
          // ! edit product
          'product_updated': 'Producto actualizado',
          // ! exchange rate
          'auto_update': 'Auto actualizar',
          'bank_rate': 'Tasa bancaria',
          'new_rate': 'Nueva tasa',
          'auto_adjust': 'Ajustar automáticamente',
          'adjust_by': 'Ajustar por',
          'manual_input': 'Entrada manual',
          'enter_amount': 'Ingrese cantidad',
          'exchange_rate_saved': 'Tasa de cambio guardada',
          // ! categories
          'delete_category': 'Eliminar categoría',
          'delete_category_confirmation':
              '¿Está seguro de que desea eliminar esta categoría?',
          'new_category': 'Nueva categoría',
          'category_name': 'Nombre de la categoría',
          'category_deleted': 'Categoría eliminada',
          'error_deleting_category': 'Error eliminando categoría',
          'edit_category': 'Editar categoría',
          'category_updated': 'Categoría actualizada',
          // ! settings
          'logout': 'Cerrar sesión',
          'logout_confirmation': '¿Está seguro de que desea cerrar sesión?',
          'notifications': 'Notificaciones',
          'dark_mode': 'Modo oscuro',
          'language': 'Idioma',
          'select_language': 'Seleccionar idioma',
          // ! support
          'support_description':
              '¿Necesitas ayuda? Siéntete libre de contactarnos.',
        },
        'ru_RU': {
          // ! generic
          'ok': 'Ок',
          'cancel': 'Отмена',
          'yes': 'Да',
          'no': 'Нет',
          'back': 'Назад',
          'next': 'Далее',
          'done': 'Готово',
          'retry': 'Повторить',
          'close': 'Закрыть',
          'delete': 'Удалить',
          'edit': 'Редактировать',
          'save': 'Сохранить',
          'send': 'Отправить',
          'search': 'Поиск',
          'clear': 'Очистить',
          'total': 'Всего',
          'reset': 'Сбросить',
          'apply': 'Применить',
          'not_found': 'Не найдено',
          'confirm': 'Подтвердить',
          'change': 'Изменить',
          'currency': 'Валюта',
          'continue': 'Продолжить',
          'name': 'Имя',
          'business_name': 'Название бизнеса',
          'phone': 'Телефон',
          'main_currency': 'Основная валюта',
          'secondary_currency': 'Вторичная валюта',
          'unnamed_client': 'Безымянный клиент',
          'date': 'Дата',
          'debt': 'Долг',
          'success': 'Успех',
          'error': 'Ошибка',
          'filter': 'Фильтр',
          'sort': 'Сортировка',
          'something_went_wrong': 'Что-то пошло не так',
          'select_image_source': 'Выберите источник изображения',
          'gallery': 'Галерея',
          'camera': 'Камера',
          'english': 'Английский',
          'russian': 'Русский',
          'uzbek': 'Узбекский',
          'spanish': 'Испанский',
          'payment': 'Оплата',
          'all': 'Все',
          // ! login
          'login': 'Вход',
          'restore_account': 'Восстановить аккаунт',
          'app_description':
              'Удобно управлять вашими продажами, доходами и товарами на складе',
          'not_phone_number': 'Пожалуйста, введите правильный номер телефона',
          // ! otp
          'verification': 'Подтверждение',
          'otp_description': 'Мы отправили SMS код на номер',
          'resend_code': 'Повторно отправить код',
          // ! register
          'account_info': 'Информация об аккаунте',
          'save_and_continue': 'Сохранить и продолжить',
          'fill_required_fields': 'Пожалуйста, заполните все обязательные поля',
          // ! home
          'exchange_rate': 'Курс валют',
          'todays_sales': 'Сегодняшние продажи',
          'all_sales': 'Все продажи',
          'clients': 'Клиенты',
          'products': 'Товары',
          'new_sale': 'Новая продажа',
          'add_product': 'Добавить товар',
          'statistics': 'Статистика',
          'categories': 'Категории',
          'settings': 'Настройки',
          'support': 'Поддержка',
          'no_secondary_currency': 'Нет вторичной валюты',
          // ! sales
          'all_clients': 'Все клиенты',
          'client': 'Клиент',
          'any_date': 'Любая дата',
          'reciept': 'Чек',
          'delete_sale': 'Удалить продажу',
          'delete_sale_confirmation':
              'Вы уверены, что хотите удалить эту продажу?',
          'sale': 'Продажа',
          // ! add sale
          'select_items': 'Выберите товары',
          'in_stock': 'В наличии',
          'selected': 'выбрано',
          'select_quantity': 'Выберите количество',
          'not_enough': 'Недостаточно',
          // ! cart
          'add_discount': 'Добавить скидку',
          'add_payment': 'Добавить оплату',
          'discount': 'Скидка',
          'add_comment': 'Добавить комментарий',
          'add_another': 'Добавить еще',
          'paid': 'Оплачено',
          'discounted_price': 'Цена со скидкой',
          'remaining': 'Осталось',
          'unpaid_amount': 'Неоплаченная сумма',
          'unpaid_amount_description':
              'Как вы хотите сохранить оставшуюся сумму?',
          'order_created': 'Заказ создан',
          'overpaid': 'Переплачено',
          'enter_discount': 'Введите скидку',
          'comment': 'Комментарий',
          'enter_comment': 'Введите комментарий',
          'no_products_in_cart': 'В корзине нет товаров',
          // ! edit sale
          'order_updated': 'Заказ обновлен',
          // ! statistics
          'today': 'Сегодня',
          'last_week': 'Последняя неделя',
          'last_month': 'Последний месяц',
          'last_year': 'Последний год',
          'all_time': 'Все время',
          'total_sales': 'Всего продаж',
          'products_sold': 'Товаров продано',
          'no_products_sold': 'Нет товаров проданных',
          'sold': 'Продано',
          // ! clients
          'no_phone': 'Нет телефона',
          'no_note': 'Нет заметки',
          'no_debt': 'Нет долга',
          'delete_client': 'Удалить клиента',
          'delete_client_confirmation':
              'Вы уверены, что хотите удалить этого клиента?',
          'view_orders': 'Заказы',
          // ! add client
          'new_client': 'Новый клиент',
          'note': 'Примечание',
          'client_added': 'Клиент добавлен',
          // ! edit client
          'edit_client': 'Редактировать клиента',
          'client_updated': 'Клиент обновлен',
          // ! select client
          'select_client': 'Выберите клиента',
          // ! products
          'product_name': 'Название товара',
          'category': 'Категория',
          'code': 'Код',
          'price': 'Цена',
          'stock_in_out': 'Добавить/Удалить товар',
          'edit_product': 'Редактировать товар',
          'make_sale': 'Сделать продажу',
          'delete_product': 'Удалить товар',
          'delete_product_confirmation':
              'Вы уверены, что хотите удалить этот товар?',
          'you_applied_filter': 'Вы применили фильтр',
          'show_all': 'Показать все',
          'deleted': 'удалено',
          'add_new_category': 'Добавить новую категорию',
          // ! add product
          'new_product': 'Новый товар',
          'no_category': 'Нет категории',
          'total_stock': 'Общий остаток',
          'product_name_required': 'Название товара обязательно',
          'product_price_required': 'Цена товара обязательна',
          'product_quantity_required': 'Количество товара обязательно',
          'price_negative': 'Цена не может быть отрицательной',
          'quantity_negative': 'Количество не может быть отрицательным',
          'product_added': 'Товар добавлен',
          // ! edit product
          'product_updated': 'Товар обновлен',
          // ! exchange rate
          'auto_update': 'Автообновление',
          'bank_rate': 'Курс банка',
          'new_rate': 'Новый курс',
          'auto_adjust': 'Автокорректировка',
          'adjust_by': 'Корректировать по',
          'manual_input': 'Ручной ввод',
          'enter_amount': 'Введите сумму',
          'exchange_rate_saved': 'Курс валют сохранен',
          // ! categories
          'delete_category': 'Удалить категорию',
          'delete_category_confirmation':
              'Вы уверены, что хотите удалить эту категорию?',
          'new_category': 'Новая категория',
          'category_name': 'Название категории',
          'category_deleted': 'Категория удалена',
          'error_deleting_category': 'Ошибка удаления категории',
          'edit_category': 'Редактировать категорию',
          'category_updated': 'Категория обновлена',
          // ! settings
          'logout': 'Выйти',
          'logout_confirmation': 'Вы уверены, что хотите выйти?',
          'notifications': 'Уведомления',
          'dark_mode': 'Темный режим',
          'language': 'Язык',
          'select_language': 'Выберите язык',
          // ! support
          'support_description':
              'Нужна помощь? Не стесняйтесь связаться с нами.'
        },
        'uz_UZ': {
          // ! generic
          'ok': 'Ok',
          'cancel': 'Orqaga',
          'yes': 'Ha',
          'no': 'Yo\'q',
          'back': 'Orqaga',
          'next': 'Keyingi',
          'done': 'Bajarildi',
          'retry': 'Qayta urinib ko\'ring',
          'close': 'Yopish',
          'delete': 'O\'chirish',
          'edit': 'O\'zgartirish',
          'save': 'Saqlash',
          'send': 'Yuborish',
          'search': 'Qidiruv',
          'clear': 'Tozalash',
          'total': 'Jami',
          'reset': 'Tozalash',
          'apply': 'Qo\'yish',
          'not_found': 'Topilmadi',
          'confirm': 'Tasdiqlash',
          'change': 'O\'zgartirish',
          'currency': 'Valyuta',
          'continue': 'Davom etish',
          'name': 'Ism',
          'business_name': 'Biznes nomi',
          'phone': 'Telefon',
          'main_currency': 'Asosiy valyuta',
          'secondary_currency': 'Ikkinchi valyuta',
          'unnamed_client': 'Ism yo\'q',
          'date': 'Sana',
          'debt': 'Qarz',
          'success': 'Muvaffaqiyat',
          'error': 'Xato',
          'filter': 'Filtrlash',
          'sort': 'Sortlash',
          'something_went_wrong': 'Xatolik yuz berdi',
          'select_image_source': 'Rasm yuklash',
          'gallery': 'Galereya',
          'camera': 'Kamera',
          'english': 'Ingliz',
          'russian': 'Rus',
          'uzbek': 'O\'zbek',
          'spanish': 'Ispan',
          'payment': 'To\'lov',
          'all': 'Hamma',
          // ! login
          'login': 'Kirish',
          'restore_account': 'Akkauntni qayta tiklash',
          'app_description':
              'Sotuvlar, foyda va tovarlaringizni oson boshqarish',
          'not_phone_number': 'To\'g\'ri telefon raqamini kiriting',
          // ! otp
          'verification': 'Tasdiqlash',
          'otp_description': 'Telefon raqamga SMS kodi yuborildi',
          'resend_code': 'Kodni qayta yuborish',
          // ! register
          'account_info': 'Akkaunt haqida ma\'lumot',
          'save_and_continue': 'Saqlash va davom etish',
          'fill_required_fields': 'Zarur bo\'lgan qaotrlarni to\'ldiring',
          // ! home
          'exchange_rate': 'Valyuta kursi',
          'todays_sales': 'Bugun sotuvlar',
          'all_sales': 'Barcha sotuvlar',
          'clients': 'Mijozlar',
          'products': 'Tovarlar',
          'new_sale': 'Yangi sotuv',
          'add_product': 'Tovar qo\'shish',
          'statistics': 'Statistika',
          'categories': 'Kategoriyalar',
          'settings': 'Sozlamalar',
          'no_secondary_currency': 'Ikkinchi valyuta yo\'q',
          // ! sales
          'all_clients': 'Barcha mijozlar',
          'client': 'Mijoz',
          'any_date': 'Hamma sana',
          'reciept': 'Sotuv',
          'delete_sale': 'Sotuvni o\'chirish',
          'delete_sale_confirmation': 'Siz sotuvni o\'chirmoqchimisiz?',
          'sale': 'Sotuv',
          // ! add sale
          'select_items': 'Tovarlarni tanlang',
          'in_stock': 'Mavjud',
          'selected': 'tanlangan',
          'select_quantity': 'Miqdorni tanlang',
          'not_enough': 'Miqdori yetarli emas',
          // ! cart
          'add_discount': 'Chegirma qo\'shish',
          'add_payment': 'To\'lov qo\'shish',
          'discount': 'Chegirma',
          'add_comment': 'Izoh qo\'shish',
          'add_another': 'Boshqa qo\'shish',
          'paid': 'To\'langan',
          'discounted_price': 'Chegirmalangan narxi',
          'remaining': 'Qoldi',
          'unpaid_amount': 'To\'lanmagan summa',
          'unpaid_amount_description':
              'Qolgan summani qay tarzda saqlash kerak?',
          'order_created': 'Sotuv yaratildi',
          'overpaid': 'Ortiqcha to\'lov',
          'enter_discount': 'Chegirma qo\'shish',
          'comment': 'Izoh',
          'enter_comment': 'Izoh qo\'shish',
          'no_products_in_cart': 'Sotuvda hech narsa yo\'q',
          // ! edit sale
          'order_updated': 'Sotuv o\'zgartirildi',
          // ! statistics
          'today': 'Bugun',
          'last_week': 'O\'tgan hafta',
          'last_month': 'O\'tgan oy',
          'last_year': 'O\'tgan yil',
          'all_time': 'Barcha vaqt',
          'total_sales': 'Jami sotuvlar',
          'products_sold': 'Sotilgan tovarlar',
          'no_products_sold': 'Tovar sotilmagan',
          'sold': 'Sotilgan',
          // ! clients
          'no_phone': 'Telefon raqami yo\'q',
          'no_note': 'Izoh yo\'q',
          'no_debt': 'Qarz yo\'q',
          'delete_client': 'Mijozni o\'chirish',
          'delete_client_confirmation': 'Mijozni o\'chirmoqchimisiz?',
          'view_orders': 'Sotuvlarni ko\'rish',
          // ! add client
          'new_client': 'Yangi mijoz',
          'note': 'Izoh',
          'client_added': 'Mijoz qo\'shildi',
          // ! edit client
          'edit_client': 'Mijozni o\'zgartirish',
          'client_updated': 'Mijoz o\'zgartirildi',
          // ! select client
          'select_client': 'Mijozni tanlang',
          // ! products
          'product_name': 'Tovar nomi',
          'category': 'Kategoriya',
          'code': 'Kodi',
          'price': 'Narxi',
          'stock_in_out': 'Miqdor qo\'shish/kamaytirish',
          'edit_product': 'Tovarni o\'zgartirish',
          'make_sale': 'Sotuv qilish',
          'delete_product': 'Tovarni o\'chirish',
          'delete_product_confirmation': 'Siz tovarni o\'chirmoqchimisiz?',
          'you_applied_filter': 'Siz filterladingiz',
          'show_all': 'Hammasini ko\'rsatish',
          'deleted': 'o\'chirildi',
          'add_new_category': 'Yangi kategoriya qo\'shish',
          // ! add product
          'new_product': 'Yangi tovar',
          'no_category': 'Kategoriya yo\'q',
          'total_stock': 'Jami',
          'product_name_required': 'Tovar nomi bo\'lishi shart',
          'product_price_required': 'Tovar narxi bo\'lishi shart',
          'product_quantity_required': 'Tovar miqdori bo\'lishi shart',
          'price_negative': 'Tovar narxi musbat bo\'lishi shart',
          'quantity_negative': 'Tovar miqdori musbat bo\'lishi shart',
          'product_added': 'Tovar qo\'shildi',
          // ! edit product
          'product_updated': 'Tovar o\'zgartirildi',
          // ! exchange rate
          'auto_update': 'Avto yangilash',
          'bank_rate': 'Bank kursi',
          'new_rate': 'Yangi kurs',
          'auto_adjust': 'Avto moslashtirish',
          'adjust_by': 'Moslashtirish',
          'manual_input': 'Qo\'shish',
          'enter_amount': 'Miqdor kiritish',
          'exchange_rate_saved': 'Kurs saqlandi',
          // ! categories
          // 'delete_category': 'Delete category',
          'delete_category': 'Kategoriya o\'chirish',
          'delete_category_confirmation': 'Kategoriya o\'chirishni istaysizmi?',
          'new_category': 'Yangi kategoriya',
          'category_name': 'Kategoriya nomi',
          'category_deleted': 'Kategoriya o\'chirildi',
          'error_deleting_category': 'Kategoriya o\'chirishda xatolik',
          "edit_category": "Kategoriya o'zgartirish",
          'category_updated': 'Kategoriya yangilandi',
          // ! settings
          'logout': 'Chiqish',
          'logout_confirmation': 'Siz chiqishingizga ishonchingiz komilmi?',
          'notifications': 'Bildirishnomalar',
          'dark_mode': 'Tungi rejim',
          'language': 'Til',
          'select_language': 'Tilni tanlang',
          // ! support
          'support_description': 'Yordam kerakmi? Biz bilan bog\'laning.',
        },
      };
}
